export const US_CITIES: Record<string, string[]> = {
  AL: [
    'Anniston',
    'Auburn',
    'Birmingham',
    'Cullman',
    'Decatur',
    'Dothan',
    'Florence',
    'Gadsden',
    'Hoover',
    'Huntsville',
    'Mobile',
    'Montgomery',
    'Phenix City',
    'Tuscaloosa',
  ],
  AK: ['Anchorage', 'Fairbanks', 'Juneau', 'Ketchikan', 'Sitka', 'Wasilla'],
  AZ: [
    'Avondale',
    'Chandler',
    'Gilbert',
    'Glendale',
    'Goodyear',
    'Mesa',
    'Peoria',
    'Phoenix',
    'Scottsdale',
    'Surprise',
    'Tempe',
    'Tucson',
    'Yuma',
  ],
  AR: [
    'Conway',
    'Fayetteville',
    'Fort Smith',
    'Jonesboro',
    'Little Rock',
    'North Little Rock',
    'Pine Bluff',
    'Rogers',
    'Springdale',
    'Texarkana',
  ],
  CA: [
    'Anaheim',
    'Bakersfield',
    'Berkeley',
    'Chula Vista',
    'Concord',
    'Escondido',
    'Fontana',
    'Fremont',
    'Fresno',
    'Fullerton',
    'Irvine',
    'Long Beach',
    'Los Angeles',
    'Modesto',
    'Oakland',
    'Ontario',
    'Oxnard',
    'Pasadena',
    'Riverside',
    'Sacramento',
    'Salinas',
    'San Bernardino',
    'San Diego',
    'San Francisco',
    'San Jose',
    'Santa Ana',
    'Santa Clara',
    'Santa Rosa',
    'Stockton',
    'Sunnyvale',
  ],
  CO: [
    'Aurora',
    'Boulder',
    'Colorado Springs',
    'Denver',
    'Fort Collins',
    'Lakewood',
    'Pueblo',
    'Thornton',
    'Westminster',
  ],
  CT: [
    'Bridgeport',
    'Bristol',
    'Hartford',
    'Meriden',
    'New Britain',
    'New Haven',
    'Norwalk',
    'Stamford',
    'Waterbury',
  ],
  DE: ['Dover', 'Newark', 'Wilmington'],
  FL: [
    'Cape Coral',
    'Clearwater',
    'Fort Lauderdale',
    'Fort Myers',
    'Gainesville',
    'Hialeah',
    'Jacksonville',
    'Lakeland',
    'Miami',
    'Naples',
    'Orlando',
    'Palm Bay',
    'Pembroke Pines',
    'Pensacola',
    'Port St. Lucie',
    'Sarasota',
    'St. Petersburg',
    'Tallahassee',
    'Tampa',
  ],
  GA: [
    'Albany',
    'Athens',
    'Atlanta',
    'Augusta',
    'Columbus',
    'Macon',
    'Marietta',
    'Roswell',
    'Savannah',
    'Warner Robins',
  ],
  HI: ['Hilo', 'Honolulu', 'Kailua', 'Kaneohe', 'Pearl City'],
  ID: [
    'Boise',
    'Caldwell',
    "Coeur d'Alene",
    'Idaho Falls',
    'Meridian',
    'Nampa',
    'Pocatello',
    'Twin Falls',
  ],
  IL: [
    'Aurora',
    'Chicago',
    'Elgin',
    'Joliet',
    'Naperville',
    'Peoria',
    'Rockford',
    'Springfield',
    'Waukegan',
  ],
  IN: [
    'Bloomington',
    'Carmel',
    'Evansville',
    'Fort Wayne',
    'Gary',
    'Hammond',
    'Indianapolis',
    'Muncie',
    'South Bend',
  ],
  IA: [
    'Ames',
    'Cedar Rapids',
    'Davenport',
    'Des Moines',
    'Dubuque',
    'Iowa City',
    'Sioux City',
    'Waterloo',
  ],
  KS: ['Kansas City', 'Lawrence', 'Manhattan', 'Olathe', 'Overland Park', 'Topeka', 'Wichita'],
  KY: ['Bowling Green', 'Covington', 'Lexington', 'Louisville', 'Owensboro'],
  LA: ['Baton Rouge', 'Kenner', 'Lafayette', 'Lake Charles', 'Monroe', 'New Orleans', 'Shreveport'],
  ME: ['Augusta', 'Bangor', 'Lewiston', 'Portland'],
  MD: ['Annapolis', 'Baltimore', 'Bowie', 'Frederick', 'Gaithersburg', 'Hagerstown', 'Rockville'],
  MA: [
    'Boston',
    'Brockton',
    'Cambridge',
    'Lowell',
    'New Bedford',
    'Newton',
    'Quincy',
    'Springfield',
    'Worcester',
  ],
  MI: [
    'Ann Arbor',
    'Detroit',
    'Flint',
    'Grand Rapids',
    'Kalamazoo',
    'Lansing',
    'Livonia',
    'Sterling Heights',
    'Warren',
  ],
  MN: [
    'Bloomington',
    'Brooklyn Park',
    'Duluth',
    'Minneapolis',
    'Plymouth',
    'Rochester',
    'St. Paul',
  ],
  MS: ['Biloxi', 'Gulfport', 'Hattiesburg', 'Jackson', 'Meridian', 'Tupelo'],
  MO: ['Columbia', 'Independence', 'Kansas City', 'Springfield', 'St. Louis'],
  MT: ['Billings', 'Bozeman', 'Great Falls', 'Helena', 'Missoula'],
  NE: ['Bellevue', 'Grand Island', 'Lincoln', 'Omaha'],
  NV: ['Henderson', 'Las Vegas', 'North Las Vegas', 'Reno', 'Sparks'],
  NH: ['Concord', 'Dover', 'Manchester', 'Nashua'],
  NJ: ['Elizabeth', 'Jersey City', 'Newark', 'Paterson', 'Trenton'],
  NM: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Roswell', 'Santa Fe'],
  NY: [
    'Albany',
    'Buffalo',
    'Mount Vernon',
    'New Rochelle',
    'New York City',
    'Rochester',
    'Schenectady',
    'Syracuse',
    'Utica',
    'Yonkers',
  ],
  NC: [
    'Asheville',
    'Cary',
    'Chapel Hill',
    'Charlotte',
    'Durham',
    'Fayetteville',
    'Greensboro',
    'High Point',
    'Raleigh',
    'Wilmington',
    'Winston-Salem',
  ],
  ND: ['Bismarck', 'Fargo', 'Grand Forks', 'Minot'],
  OH: ['Akron', 'Cincinnati', 'Cleveland', 'Columbus', 'Dayton', 'Toledo', 'Youngstown'],
  OK: ['Broken Arrow', 'Edmond', 'Lawton', 'Norman', 'Oklahoma City', 'Tulsa'],
  OR: ['Bend', 'Eugene', 'Gresham', 'Hillsboro', 'Portland', 'Salem'],
  PA: ['Allentown', 'Erie', 'Philadelphia', 'Pittsburgh', 'Reading', 'Scranton'],
  RI: ['Cranston', 'Pawtucket', 'Providence', 'Warwick', 'Woonsocket'],
  SC: [
    'Charleston',
    'Columbia',
    'Greenville',
    'Mount Pleasant',
    'North Charleston',
    'Rock Hill',
    'Spartanburg',
  ],
  SD: ['Aberdeen', 'Rapid City', 'Sioux Falls'],
  TN: [
    'Chattanooga',
    'Clarksville',
    'Jackson',
    'Johnson City',
    'Knoxville',
    'Memphis',
    'Murfreesboro',
    'Nashville',
  ],
  TX: [
    'Abilene',
    'Amarillo',
    'Arlington',
    'Austin',
    'Beaumont',
    'Corpus Christi',
    'Dallas',
    'El Paso',
    'Fort Worth',
    'Frisco',
    'Garland',
    'Grand Prairie',
    'Houston',
    'Irving',
    'Killeen',
    'Laredo',
    'Lubbock',
    'McAllen',
    'McKinney',
    'Mesquite',
    'Midland',
    'Odessa',
    'Pasadena',
    'Plano',
    'Round Rock',
    'San Antonio',
    'Tyler',
    'Waco',
    'Wichita Falls',
  ],
  UT: [
    'Layton',
    'Ogden',
    'Orem',
    'Provo',
    'Salt Lake City',
    'Sandy',
    'St. George',
    'West Jordan',
    'West Valley City',
  ],
  VT: ['Burlington', 'Essex', 'Montpelier', 'Rutland'],
  VA: [
    'Alexandria',
    'Arlington',
    'Chesapeake',
    'Hampton',
    'Newport News',
    'Norfolk',
    'Richmond',
    'Roanoke',
    'Virginia Beach',
  ],
  WA: ['Bellevue', 'Everett', 'Kirkland', 'Renton', 'Seattle', 'Spokane', 'Tacoma', 'Vancouver'],
  WV: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'],
  WI: ['Appleton', 'Green Bay', 'Kenosha', 'Madison', 'Milwaukee', 'Oshkosh', 'Racine'],
  WY: ['Casper', 'Cheyenne', 'Laramie'],
};
